### ISSUE TITLE
Lantern Pro Authentication

### ISSUE THREAD

**Issue by igorcn** [EasyPi/docker-lantern-arm#1]
Hi, Thank you for your raspbian built version of lantern. And I am a lantern pro user. Could you please tell me how to authenticate raspbian lantern to pro version?

**Comment by vimagick** [comment]
I'm not sure free version of lantern uses the same protocol as pro version.
Type `lantern -help` in terminal to see what options it provide.

**Comment by just4id** [comment]
In my mind, running lantern server means it's lantern pro. ;)

**Comment by baiking** [comment]
same question here,need to login as pro

**Comment by just4id** [comment]
lantern_4.4.0-1_armhf.deb not work properly any more on my Raspberry Pi Zero, should be lantern issue.
